# product_optimizor = []
[[footer_menu_1]]
name = "Compage"
url = "/compage"
weight = 1
[[footer_menu_1]]
name = "Capten"
url = "/capten"
weight = 2
[[footer_menu_1]]
name = "QualityTrace"
url = "/quality-trace"
weight = 3
[[footer_menu_1]]
name = "Opty"
url = "/opty"
weight = 4
[[footer_menu_1]]
name = "KubViz"
url = "/kubviz"
weight = 5
[[footer_menu_1]]
name = "Tarian"
url = "/tarian"
weight = 6


[[footer_menu_2]]
name = "Blogs"
url = "/blog"
weight = 1
[[footer_menu_2]]
name = "Show case"
url = "/showcase"
weight = 2
# [[footer_menu_2]]
# name = "Tools"
# url = "/tool"
# weight = 3

# [[footer_menu_2]]
# name = "Mindmaps"
# url = "/mindmaps"
# weight = 3

# [[footer_menu_2]]
# name = "Our OpenSource Projects"
# url = "/kubviz"
# weight = 5
# [[footer_menu_2]]
# name = "Contributed OpenSource Projects"
# url = "/tarian"
# weight = 6

# [[footer_menu_3]]
# name = "Services"
# url = "/services-form/"
# weight = 1
# [[footer_menu_3]]
# name = "Certified Partner Program"
# url = "/certified-partner-program/"
# weight = 2
[[footer_menu_3]]
name = "About Us"
url = "/about/"
weight = 1

[[footer_menu_3]]
name = "Contact Us"
url = "/contact/"
weight = 1
# [[footer_menu_3]]
# name = "Privacy Policy"
# url = "#!"
# weight = 4
# [[footer_menu_3]]
# name = "Terms & Conditions"
# url = "/licensing-terms-conditions/2-terms-and-conditions"
# weight = 5
# [[footer_menu_3]]
# name = "Licensing"
# url = "/licensing-terms-conditions/1-licensing"
# weight = 6

# [[footer_menu_4]]
# name = "About Us"
# url = "/about/"
# weight = 1

[[footer_menu_4]]
name = "Privacy policy"
url = "/privacy-policy/"
weight = 1


[[footer_menu_5]]
name = "Disclaimer"
url = "/disclaimer/"
weight = 1


# [[footer_menu_4]]
# name = "Login"
# url = "https://capten.cloud/"
# weight = 3
# [[footer_menu_4]]
# name = "Sign Up"
# url = "https://capten.cloud/"
# weight = 4

# Display Home button in Header menu bar on top
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blogs"
url = "blog/"
weight = 20

[[main]]
name = "Showcase"
url = "showcase/"
weight = 25

[[main]]
name = "Resources"
url = "documents/"
weight = 30

[[main]]
name = "About"
url = "/about/"
weight = 40

[[main]]
name = "Contact"
url = "/contact/"
weight = 50



