#################### default parameters ################################
favicon = "images/favicon/android-chrome-192x192.png"
image = "images/logo.svg"
logo = "images/logo.svg"
logo_light = "images/logo.svg"
logo_dark = "images/logo.svg"
logo_footer = "images/logo-footer.png"
footer_logo_dark = false
logo_webp = false
logo_text = "Lindane.co"
logo_width = "130px"
# Main Sections
mainSections = ["blog"]

google_tag_manager = ""
google_adsense = ""

mobile = ""
email = "linhhv.work@gmail.com"
description = ""


fullSiteSearch = true
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""

# Contact Form Action
career_form_action = "#!"
contact_form_action = "#!"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Business", "Marketing", "SEO", "SaaS", "Android", "Ios", "Monetization", "Technology", "Review", "Cloud-Native", "Ai", "DevOps", "Kubernetes", "Talent", "Book"]
description = "SaaS strategies, marketing insights, and expert knowledge. Boost your business with actionable tips and industry trends. Join our community of innovators."
author = "LinDane"
image = "images/og-image.png"


# Footer Configuration
[footer]
footer_light = false
# bg_color = "#1e384c"
# bg_image = "images/bg-banner-page.jpg"
bg_image_overlay_color = "rgba(0,0,0,.65)"


# Call To Action
[call_to_action]
enable = false
title = "Looking for Cloud-Native Implementation?"
image = "images/footer/homepage/contact-image.svg"
subtitle = "Finding the right talent is pain. More so, keeping up with concepts, culture, technology and tools. We all have been there. Our AI-based automated solutions helps eliminate these issues, making your teams lives easy."
button_label = "Contact Us"
button_link = "contact/"


# Call To Action
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2


[navigation_button]
enable = false
icon = "far fa-user"
label = "Log In"
link = "#!"

[navigation_button_two]
enable = false
label = "Sign Up Now"
link = "#!"


[preloader]
enable = false
preloader = "images/loader.png"

[clickup_form]
enable = true

[newsletter]
enable = true
clickup_iframe_url = ""
button_label = "Subscribe for Newsletter"

[blog_popup]
enable = false
clickup_iframe_url = ""

[learning_center_popup]
enable = false
clickup_iframe_url = ""

[opensource_security_reporting]
enable = false
clickup_iframe_url = ""

[product_demo_request_form]
enable = false
clickup_iframe_url = ""

[upcoming_events_popup_form]
enable = false
clickup_iframe_url = ""

[ondemand_events_popup_form]
enable = false
clickup_iframe_url = ""

[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/lllindane"
title = "X"
[[social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/hoang-van-linh-173362256/"
title = "Linkedin"
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/profile.php?id=61562039192202"
title = "Facebook"
[[social]]
icon = "fab fa-telegram"
link = "https://t.me/binarybearcomunity"
title = "Telegram"
[[social]]
icon = "fab fa-youtube"
link = "https://www.youtube.com/@lindanehere"
title = "Youtube"
